export default {
  FORM_CONTROL_DISPLAY_EXTRA: 'FORM_CONTROL_DISPLAY_EXTRA',
  FORM_CONTROL_DISPLAY_CONTROL: 'FORM_CONTROL_DISPLAY_CONTROL',
  FORM_CONTROL_DISPLAY_EFFECT: 'FORM_CONTROL_DISPLAY_EFFECT',
};
